-- 4. Create trades table for financial tracking
create table if not exists trades (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  asset text not null,
  type text not null check (type in ('long', 'short')),
  entry_price numeric not null,
  exit_price numeric,
  status text default 'open' check (status in ('open', 'closed')),
  notes text
);

-- Enable RLS
alter table trades enable row level security;

-- Create policy for authenticated access (adjust as needed for your app)
create policy "Allow authenticated users to manage trades" on trades
  for all using (auth.role() = 'authenticated');
